// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v5.27.1
// source: amino/amino.proto

/* eslint-disable */

export const protobufPackage = 'amino';
