import { Chain } from '@xdefi-tech/chains-core';

export enum EVMChains {
  ethereum = 'ethereum',
  smartchain = 'smartchain',
  polygon = 'polygon',
  avalanche = 'avalanche',
  fantom = 'fantom',
  arbitrum = 'arbitrum',
  aurora = 'aurora',
  cantoevm = 'cantoevm',
  optimism = 'optimism',
  klaytn = 'klaytn',
  cronos = 'cronos',
  gnosis = 'gnosis',
  base = 'base',
  blast = 'blast',
  zkSync = 'zkSync',
}

export interface EVMChainManifest extends Chain.Manifest {
  maxGapAmount?: number;
}

export const EVM_MANIFESTS: {
  [key in EVMChains]: EVMChainManifest;
} = {
  [EVMChains.ethereum]: {
    name: 'Ethereum',
    description: '',
    rpcURL: 'https://ethereum-mainnet.xdefiservices.com',
    chainSymbol: 'ETH',
    blockExplorerURL: 'https://etherscan.io',
    chainId: '1',
    chain: 'ethereum',
    decimals: 18,
    feeGasStep: {
      high: 1.5,
      medium: 1.25,
      low: 1,
    },
    multicallContractAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
    maxGapAmount: 0,
  },
  [EVMChains.smartchain]: {
    name: 'BNB Smart Chain',
    description: '',
    rpcURL: 'https://bsc-dataseed1.defibit.io',
    chainSymbol: 'BNB',
    blockExplorerURL: 'https://bscscan.com',
    chainId: '56',
    chain: 'smartchain',
    decimals: 18,
    feeGasStep: {
      high: 1.5,
      medium: 1.25,
      low: 1,
    },
    multicallContractAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
    maxGapAmount: 0,
  },
  [EVMChains.polygon]: {
    name: 'Polygon',
    description: '',
    rpcURL: 'https://polygon-mainnet.xdefiservices.com',
    chainSymbol: 'MATIC',
    blockExplorerURL: 'https://polygonscan.com',
    chainId: '137',
    chain: 'polygon',
    decimals: 18,
    feeGasStep: {
      high: 1.5,
      medium: 1.25,
      low: 1,
    },
    multicallContractAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
    maxGapAmount: 0,
  },
  [EVMChains.avalanche]: {
    name: 'Avalanche',
    description: '',
    rpcURL: 'https://avax-rpcs.xdefiservices.com',
    chainSymbol: 'AVAX',
    blockExplorerURL: 'https://snowtrace.io',
    chainId: '43114',
    chain: 'avalanche',
    decimals: 18,
    feeGasStep: {
      high: 1.5,
      medium: 1.25,
      low: 1,
    },
    multicallContractAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
    maxGapAmount: 0,
  },
  [EVMChains.fantom]: {
    name: 'Fantom',
    description: '',
    rpcURL: 'https://fantom-mainnet.xdefiservices.com',
    chainSymbol: 'FTM',
    blockExplorerURL: 'https://ftmscan.com',
    chainId: '250',
    chain: 'fantom',
    decimals: 18,
    feeGasStep: {
      high: 3,
      medium: 3,
      low: 3,
    },
    multicallContractAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
    maxGapAmount: 0,
  },
  [EVMChains.arbitrum]: {
    name: 'Arbitrum',
    description: '',
    rpcURL: 'https://arbitrum-rpcs.xdefiservices.com',
    chainSymbol: 'ETH',
    blockExplorerURL: 'https://arbiscan.io',
    chainId: '42161',
    chain: 'arbitrum',
    decimals: 18,
    feeGasStep: {
      high: 1,
      medium: 1,
      low: 1,
    },
    multicallContractAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
    maxGapAmount: 0,
  },
  [EVMChains.aurora]: {
    name: 'Aurora',
    description: '',
    rpcURL: 'https://aurora-rpc.xdefiservices.com',
    chainSymbol: 'ETH',
    blockExplorerURL: 'https://aurorascan.dev',
    chainId: '1313161554',
    chain: 'aurora',
    decimals: 18,
    feeGasStep: {
      high: 1.5,
      medium: 1.25,
      low: 1,
    },
    multicallContractAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
    maxGapAmount: 0,
  },
  [EVMChains.cantoevm]: {
    name: 'Canto EVM',
    description: '',
    rpcURL: 'https://canto-rpc.xdefiservices.com',
    chainSymbol: 'CANTO',
    blockExplorerURL: 'https://cantoscan.com',
    chainId: '7700',
    chain: 'cantoevm',
    decimals: 18,
    feeGasStep: {
      high: 1.5,
      medium: 1.25,
      low: 1,
    },
    multicallContractAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
    maxGapAmount: 0,
  },
  [EVMChains.optimism]: {
    name: 'Optimism',
    description: '',
    rpcURL: 'https://rpc-proxy.xdefi.services/optimism',
    chainSymbol: 'ETH',
    blockExplorerURL: 'https://optimistic.etherscan.io',
    chainId: '10',
    chain: 'optimism',
    decimals: 18,
    feeGasStep: {
      high: 1.5,
      medium: 1.25,
      low: 1,
    },
    multicallContractAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
    maxGapAmount: 0,
  },
  [EVMChains.klaytn]: {
    name: 'Klaytn',
    description: '',
    rpcURL: 'https://rpc-proxy.xdefi.services/klaytn',
    chainSymbol: 'KLAY',
    blockExplorerURL: 'https://klaytnscope.com',
    chainId: '8217',
    chain: 'klaytn',
    decimals: 18,
    feeGasStep: {
      high: 1.5,
      medium: 1.25,
      low: 1,
    },
    multicallContractAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
    maxGapAmount: 0,
  },
  [EVMChains.cronos]: {
    name: 'Cronos',
    description: '',
    rpcURL: 'https://evm.cronos.org',
    chainSymbol: 'CRO',
    blockExplorerURL: 'https://cronoscan.com',
    chainId: '25',
    chain: 'cronos',
    decimals: 18,
    feeGasStep: {
      high: 1.5,
      medium: 1.25,
      low: 1,
    },
    multicallContractAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
    maxGapAmount: 0,
  },
  [EVMChains.gnosis]: {
    name: 'Gnosis',
    description: '',
    rpcURL: 'https://rpc-proxy.xdefi.services/gnosis',
    chainSymbol: 'XDAI',
    blockExplorerURL: 'https://gnosisscan.io',
    chainId: '100',
    chain: 'gnosis',
    decimals: 18,
    feeGasStep: {
      high: 1.5,
      medium: 1.25,
      low: 1,
    },
    multicallContractAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
    maxGapAmount: 0,
  },
  [EVMChains.base]: {
    name: 'Base',
    description: '',
    rpcURL: 'https://rpc-proxy.xdefi.services/base/rpc/mainnet',
    chainSymbol: 'ETH',
    blockExplorerURL: 'https://basescan.org',
    chainId: '8453',
    chain: 'base',
    decimals: 18,
    feeGasStep: {
      high: 1.5,
      medium: 1.25,
      low: 1,
    },
    multicallContractAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
    maxGapAmount: 0,
  },
  [EVMChains.blast]: {
    name: 'Blast',
    description: '',
    rpcURL: 'https://rpc-proxy.xdefi.services/blast/rpc/mainnet',
    chainSymbol: 'ETH',
    blockExplorerURL: 'https://blastscan.io',
    chainId: '81457',
    chain: 'blast',
    decimals: 18,
    feeGasStep: {
      high: 1.5,
      medium: 1.25,
      low: 1,
    },
    multicallContractAddress: '0xcA11bde05977b3631167028862bE2a173976CA11',
    maxGapAmount: 0,
  },
  [EVMChains.zkSync]: {
    name: 'zkSync',
    description: '',
    rpcURL: 'https://rpc-proxy.xdefi.services/zksync/rpc/mainnet',
    chainSymbol: 'ETH',
    blockExplorerURL: 'https://explorer.zksync.io',
    chainId: '324',
    chain: 'zkSync',
    decimals: 18,
    feeGasStep: {
      high: 1.5,
      medium: 1.25,
      low: 1,
    },
    multicallContractAddress: '0xF9cda624FBC7e059355ce98a31693d299FACd963',
    maxGapAmount: 0,
  },
};

export const EVM_INDEXER_CHAIN: {
  [key in string]: string;
} = {
  [EVMChains.ethereum]: 'ethereum',
  [EVMChains.smartchain]: 'binanceSmartChain',
  [EVMChains.polygon]: 'polygon',
  [EVMChains.avalanche]: 'avalanche',
  [EVMChains.fantom]: 'fantom',
  [EVMChains.arbitrum]: 'arbitrum',
  [EVMChains.aurora]: 'aurora',
  [EVMChains.cantoevm]: 'cantoEVM',
  [EVMChains.optimism]: 'optimism',
  [EVMChains.klaytn]: 'klaytn',
  [EVMChains.cronos]: 'cronosEVM',
  [EVMChains.gnosis]: 'gnosis',
  [EVMChains.base]: 'base',
  [EVMChains.blast]: 'blast',
  [EVMChains.zkSync]: 'zkSync',
};
